from __future__ import annotations


def get_io_descriptors(mode: str) -> dict:
    """Return manual IO descriptors for the Bimo direct RL task."""
    obs_terms = [
        {
            "name": "imu_history_roll_pitch",
            "shape": [8],
            "dtype": "float32",
            "description": (
                "Four-step history of roll and pitch. "
                "Order: [t-3 roll, pitch, ..., t roll, pitch]."
            ),
        },
        {
            "name": "imu_history_gyro",
            "shape": [12],
            "dtype": "float32",
            "description": (
                "Four-step history of body angular velocity xyz. "
                "Order: [t-3 wx, wy, wz, ..., t wx, wy, wz]."
            ),
        },
        {
            "name": "action_history",
            "shape": [32],
            "dtype": "float32",
            "description": (
                "Four-step history of commanded joint actions for eight joints. "
                "Order: [t-3 a0..a7, ..., t a0..a7]."
            ),
        },
    ]

    if mode == "turn":
        obs_terms.insert(
            0,
            {
                "name": "turn_direction",
                "shape": [1],
                "dtype": "float32",
                "description": "Turn command scalar.",
            },
        )

    obs_dim = 53 if mode == "turn" else 52

    return {
        "policy": {
            "name": "bimo_policy",
            "framework": "onnx",
        },
        "observations": {
            "policy": obs_terms,
        },
        "actions": [
            {
                "name": "joint_position_action",
                "shape": [8],
                "dtype": "float32",
                "description": "Normalized action for eight joints.",
                "joint_names": [
                    "RHip",
                    "LHip",
                    "RShoulder",
                    "LShoulder",
                    "RKnee",
                    "LKnee",
                    "RAnkle",
                    "LAnkle",
                ],
            }
        ],
        "meta": {
            "task": "Bimo",
            "mode": mode,
            "observation_dim": obs_dim,
            "action_dim": 8,
            "notes": [
                "Manual descriptor for the direct RL environment.",
                "This file is not generated by Isaac Lab manager-based IO descriptor export.",
            ],
        },
    }